// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/frontend/tsuki-ui/node_modules/dumi/theme-default/slots/SourceCodeEditor/index.js';
