// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { HelmetProvider } from 'D:/frontend/tsuki-ui/node_modules/.pnpm/@umijs+renderer-react@4.6.2_865a71fd0efd2c3a193189ce8c0c2df9/node_modules/@umijs/renderer-react';
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
