// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout","meta":{"_atom_route":true}},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'D:/frontend/tsuki-ui/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.2_18ba51bf0ba351a3bd1d92a1414aaa5f/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'D:/frontend/tsuki-ui/packages/docs/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'D:/frontend/tsuki-ui/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.2_18ba51bf0ba351a3bd1d92a1414aaa5f/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'D:/frontend/tsuki-ui/packages/docs/docs/getting-started.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/frontend/tsuki-ui/packages/docs/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "packages__ui__src__alert__index.md" */'D:/frontend/tsuki-ui/packages/ui/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "packages__ui__src__button__index.md" */'D:/frontend/tsuki-ui/packages/ui/src/button/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'D:/frontend/tsuki-ui/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.2_18ba51bf0ba351a3bd1d92a1414aaa5f/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
