// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/frontend/tsuki-ui/node_modules/.pnpm/dumi@2.4.23_@babel+core@7.2_18ba51bf0ba351a3bd1d92a1414aaa5f/node_modules/dumi/theme-default/builtins/Previewer/index.js';
